language: python

python:
  - "2.7"
  - "3.5"

env:
  - PENDULUM_EXTENSIONS=true
  - PENDULUM_EXTENSIONS=false

before_install:
  - pip install codecov

install:
  - pip install -r tests-requirements.txt

script: py.test --cov=pendulum --cov-config=.coveragerc tests/

after_success:
  - codecov
