build: false

environment:
  matrix:
    - PYTHON: "C:/Python36"
    - PYTHON: "C:/Python36-x64"

install:
  - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"

  # Upgrade to the latest version of pip to avoid it displaying warnings
  # about it being out of date.
  - "pip install --disable-pip-version-check --user --upgrade pip"

  # Create poetry virtualenv
  - pip install virtualenv
  - virtualenv --python="C:/Python36-x64\\python.exe" "venv-poetry"
  - venv-poetry\\Scripts\\pip.exe install poetry --pre

  # Create current python virtualenv
  - python -m virtualenv venv
  - venv\Scripts\activate.bat
  - "SET VIRTUAL_ENV=venv"  # Seems that activate.bat does not set VIRTUAL_ENV

  # Install dependencies
  - pip install codecov
  - venv-poetry\\Scripts\\poetry.exe install -v

test_script:
  - "pytest --cov=pendulum --cov-config=.coveragerc tests/"

after_test:
  - "codecov"
