build: false

environment:
  matrix:
    - PYTHON: "C:/Python27"
    - PYTHON: "C:/Python27-x64"
    - PYTHON: "C:/Python36"
    - PYTHON: "C:/Python36-x64"

cache:
  - '%LocalAppData%\pip\Cache'
  - '%LocalAppData%\pypoetry\Cache'


install:
  - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"

  # Upgrade to the latest version of pip to avoid it displaying warnings
  # about it being out of date.
  - "python -m pip install --disable-pip-version-check --user --upgrade pip"

  # Downloading and installing poetry
  - python -m pip install poetry -U

  # Install dependencies
  - python -m pip install codecov
  - poetry install -v

test_script:
  - "poetry run pytest --cov=pendulum --cov-config=.coveragerc tests/ -W ignore"

after_test:
  - "codecov"
