[tool.poetry]
name = "pendulum"
version = "2.0.4"
description = "Python datetimes made easy"
authors = ["SÃ©bastien Eustace <sebastien@eustace.io>"]
license = "MIT"

readme = 'README.rst'

homepage = "https://pendulum.eustace.io"
repository = "https://github.com/sdispater/pendulum"
documentation = "https://pendulum.eustace.io/docs"

keywords = ['datetime', 'date', 'time']

build = "build.py"


[tool.poetry.dependencies]
python = "~2.7 || ^3.4"
python-dateutil = "^2.6"
pytzdata = ">=2018.3"

# typing is needed for Python < 3.5
typing = { version = "^3.6", python = "<3.5" }

[tool.poetry.dev-dependencies]
pytest = "^3.4"
pytest-cov = "^2.5"
pytz = ">=2018.3"
babel = "^2.5"
cleo = "^0.6.1"
tox = "^3.0"
black = { version = "^18.4-alpha.0", python = "^3.6" }
pre-commit = "^1.10"


[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
