[tool.poetry]
name = "pendulum"
version = "2.0.0a0"
description = "Python datetimes made easy"
authors = ["SÃ©bastien Eustace <sebastien@eustace.io>"]
license = "MIT"

readme = 'README.rst'

homepage = "https://pendulum.eustace.io"
repository = "https://github.com/sdispater/pendulum"
documentation = "https://pendulum.eustace.io/docs"

keywords = ['datetime', 'date', 'time']

build = "build.py"


[tool.poetry.dependencies]
python = "^3.6"
tzlocal = "^1.3"
python-dateutil = "^2.6"
pytzdata = ">=2018.3"

[tool.poetry.dev-dependencies]
pytest = "^3.4"
pytest-cov = "^2.5"
pytz = ">=2018.3"
babel = "^2.5"
cleo = "^0.6.1"
